### ISSUE TITLE
UnboundLocalError: local variable 'r' referenced before assignment

### ISSUE THREAD

**Issue by AstroMich29** [Vdesnoux/Solex_ser_recon#18]
Hi,

Thanks for the amazing work, this looks really cool :)

I have downloaded `Inti` from [here](http://valerie.desnoux.free.fr/inti/), and running it on my SER file. After some initial quick processing I get the following error (sorry for the display, I've had to use a free desktop recorder to have access to the actual error, because the crash made the window to disapear)

![image](https://user-images.githubusercontent.com/132486501/235985580-20fc4fd0-c3e9-4c6e-bdbd-ddf63b44a51a.png)

I've also ran it on the observation [12_08_34](http://www.astrosurf.com/solex/download/12_08_34.zip) avilable [here](http://www.astrosurf.com/solex/sol-ex-traitement.html) and it ran without problem. Seems like a bug in the code, but I don't understand why my obervation is bringing the code there while the example observation doesn't.

I'm not sure what to try next, would you have any idea? My observation is not really good, but I can post it somewhere if this can be of any help.

Best wishes!

**Comment by Vdesnoux** [comment]
Thanks for the console capture. I can see it cannot detect the sun edges. It is important you start to scan ´in the dark’ meaning before the sun appears and stop after the sun disappear. If you prefer, you can also share the scan with wetransfer or equivalent but I guess that’s the issue.We will cet it work !!ValerieLe 3 mai 2023 à 19:01, AstroMich29 ***@***.***> a écrit :﻿
Hi,
Thanks for the amazing work, this looks really cool :)
I have downloaded Inti from here, and running it on my SER file. After some initial quick processing I get the following error (sorry for the display, I've had to use a free desktop recorder to have access to the actual error, because the crash made the window to disapear)

I've also ran it on the observation 12_08_34 avilable here and it ran without problem. Seems like a bug in the code, but I don't understand why my obervation is bringing the code there while the example observation doesn't.
I'm not sure what to try next, would you have any idea? My observation is not really good, but I can post it somewhere if this can be of any help.
Best wishes!

**Comment by AstroMich29** [comment]
Hi @Vdesnoux thanks for your answer. I've looked at the detail of my observation against the reference one and I see that the way I scanned the sun might indeed be wrong as you suggested. I will redo the observation when the sun shows up again :) I close the issue for now and I'll reopen later if needed. Thanks again for your response!
